output   = "./internal/models"
wipe     = true
pkgname  = "models"
add-enum-types = true
add-global-variants = true

[psql]
  dbname = "tgram_subs"
  host   = "localhost"
  port   = 5432
  user   = "root"
  pass   = "secret"
  sslmode = "disable"
