// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package models

import (
	"context"
)

type Querier interface {
	DeleteAll(ctx context.Context) error
	DeleteCreator(ctx context.Context, creatorID int64) error
	DeleteSub(ctx context.Context, arg DeleteSubParams) error
	DeleteSubCreator(ctx context.Context, creatorID int64) error
	DeleteSubUser(ctx context.Context, userID int64) error
	DeleteTguser(ctx context.Context, userID int64) error
	FindCreatorID(ctx context.Context, creatorID int64) (*Creator, error)
	FindCreatorTelegramID(ctx context.Context, creatorID int64) (*Creator, error)
	FindSubHistory(ctx context.Context, subHistID int64) (*SubHistory, error)
	FindSubID(ctx context.Context, arg FindSubIDParams) (*Sub, error)
	FindTguserID(ctx context.Context, userID int64) (*Tguser, error)
	FindTguserTelegramID(ctx context.Context, telegramID int64) (*Tguser, error)
	InsertCreator(ctx context.Context, arg InsertCreatorParams) (*Creator, error)
	InsertSub(ctx context.Context, arg InsertSubParams) (*Sub, error)
	InsertSubHistory(ctx context.Context, arg InsertSubHistoryParams) (*SubHistory, error)
	InsertTguser(ctx context.Context, arg InsertTguserParams) (*Tguser, error)
	IsExistCreator(ctx context.Context, telegramID int64) (bool, error)
	IsExistSub(ctx context.Context, arg IsExistSubParams) (bool, error)
	IsExistTguser(ctx context.Context, telegramID int64) (bool, error)
	ListCreator(ctx context.Context, arg ListCreatorParams) ([]*Creator, error)
	ListSub(ctx context.Context, arg ListSubParams) ([]*Sub, error)
	ListTguser(ctx context.Context, arg ListTguserParams) ([]*Tguser, error)
	SaveSub(ctx context.Context, arg SaveSubParams) (*SubHistory, error)
	UpdateCreator(ctx context.Context, arg UpdateCreatorParams) (*Creator, error)
	UpdateSub(ctx context.Context, arg UpdateSubParams) (*Sub, error)
	UpdateTguser(ctx context.Context, arg UpdateTguserParams) (*Tguser, error)
}

var _ Querier = (*Queries)(nil)
