// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account          string
	SchemaMigrations string
	Sub              string
	SubHistory       string
	Tguser           string
}{
	Account:          "account",
	SchemaMigrations: "schema_migrations",
	Sub:              "sub",
	SubHistory:       "sub_history",
	Tguser:           "tguser",
}
