// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Creator is an object representing the database table.
type Creator struct {
	CreatorID  int64       `boil:"creator_id" json:"creator_id" toml:"creator_id" yaml:"creator_id"`
	TelegramID int64       `boil:"telegram_id" json:"telegram_id" toml:"telegram_id" yaml:"telegram_id"`
	Username   string      `boil:"username" json:"username" toml:"username" yaml:"username"`
	Password   null.Bytes  `boil:"password" json:"password,omitempty" toml:"password" yaml:"password,omitempty"`
	Email      null.String `boil:"email" json:"email,omitempty" toml:"email" yaml:"email,omitempty"`
	ChanName   null.String `boil:"chan_name" json:"chan_name,omitempty" toml:"chan_name" yaml:"chan_name,omitempty"`

	R *creatorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L creatorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CreatorColumns = struct {
	CreatorID  string
	TelegramID string
	Username   string
	Password   string
	Email      string
	ChanName   string
}{
	CreatorID:  "creator_id",
	TelegramID: "telegram_id",
	Username:   "username",
	Password:   "password",
	Email:      "email",
	ChanName:   "chan_name",
}

var CreatorTableColumns = struct {
	CreatorID  string
	TelegramID string
	Username   string
	Password   string
	Email      string
	ChanName   string
}{
	CreatorID:  "creator.creator_id",
	TelegramID: "creator.telegram_id",
	Username:   "creator.username",
	Password:   "creator.password",
	Email:      "creator.email",
	ChanName:   "creator.chan_name",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Bytes struct{ field string }

func (w whereHelpernull_Bytes) EQ(x null.Bytes) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Bytes) NEQ(x null.Bytes) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Bytes) LT(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Bytes) LTE(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Bytes) GT(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Bytes) GTE(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Bytes) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Bytes) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var CreatorWhere = struct {
	CreatorID  whereHelperint64
	TelegramID whereHelperint64
	Username   whereHelperstring
	Password   whereHelpernull_Bytes
	Email      whereHelpernull_String
	ChanName   whereHelpernull_String
}{
	CreatorID:  whereHelperint64{field: "\"creator\".\"creator_id\""},
	TelegramID: whereHelperint64{field: "\"creator\".\"telegram_id\""},
	Username:   whereHelperstring{field: "\"creator\".\"username\""},
	Password:   whereHelpernull_Bytes{field: "\"creator\".\"password\""},
	Email:      whereHelpernull_String{field: "\"creator\".\"email\""},
	ChanName:   whereHelpernull_String{field: "\"creator\".\"chan_name\""},
}

// CreatorRels is where relationship names are stored.
var CreatorRels = struct {
	Subs         string
	SubHistories string
}{
	Subs:         "Subs",
	SubHistories: "SubHistories",
}

// creatorR is where relationships are stored.
type creatorR struct {
	Subs         SubSlice        `boil:"Subs" json:"Subs" toml:"Subs" yaml:"Subs"`
	SubHistories SubHistorySlice `boil:"SubHistories" json:"SubHistories" toml:"SubHistories" yaml:"SubHistories"`
}

// NewStruct creates a new relationship struct
func (*creatorR) NewStruct() *creatorR {
	return &creatorR{}
}

func (r *creatorR) GetSubs() SubSlice {
	if r == nil {
		return nil
	}
	return r.Subs
}

func (r *creatorR) GetSubHistories() SubHistorySlice {
	if r == nil {
		return nil
	}
	return r.SubHistories
}

// creatorL is where Load methods for each relationship are stored.
type creatorL struct{}

var (
	creatorAllColumns            = []string{"creator_id", "telegram_id", "username", "password", "email", "chan_name"}
	creatorColumnsWithoutDefault = []string{"telegram_id", "username"}
	creatorColumnsWithDefault    = []string{"creator_id", "password", "email", "chan_name"}
	creatorPrimaryKeyColumns     = []string{"creator_id"}
	creatorGeneratedColumns      = []string{}
)

type (
	// CreatorSlice is an alias for a slice of pointers to Creator.
	// This should almost always be used instead of []Creator.
	CreatorSlice []*Creator
	// CreatorHook is the signature for custom Creator hook methods
	CreatorHook func(context.Context, boil.ContextExecutor, *Creator) error

	creatorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	creatorType                 = reflect.TypeOf(&Creator{})
	creatorMapping              = queries.MakeStructMapping(creatorType)
	creatorPrimaryKeyMapping, _ = queries.BindMapping(creatorType, creatorMapping, creatorPrimaryKeyColumns)
	creatorInsertCacheMut       sync.RWMutex
	creatorInsertCache          = make(map[string]insertCache)
	creatorUpdateCacheMut       sync.RWMutex
	creatorUpdateCache          = make(map[string]updateCache)
	creatorUpsertCacheMut       sync.RWMutex
	creatorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var creatorAfterSelectHooks []CreatorHook

var creatorBeforeInsertHooks []CreatorHook
var creatorAfterInsertHooks []CreatorHook

var creatorBeforeUpdateHooks []CreatorHook
var creatorAfterUpdateHooks []CreatorHook

var creatorBeforeDeleteHooks []CreatorHook
var creatorAfterDeleteHooks []CreatorHook

var creatorBeforeUpsertHooks []CreatorHook
var creatorAfterUpsertHooks []CreatorHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Creator) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Creator) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Creator) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Creator) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Creator) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Creator) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Creator) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Creator) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Creator) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range creatorAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCreatorHook registers your hook function for all future operations.
func AddCreatorHook(hookPoint boil.HookPoint, creatorHook CreatorHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		creatorAfterSelectHooks = append(creatorAfterSelectHooks, creatorHook)
	case boil.BeforeInsertHook:
		creatorBeforeInsertHooks = append(creatorBeforeInsertHooks, creatorHook)
	case boil.AfterInsertHook:
		creatorAfterInsertHooks = append(creatorAfterInsertHooks, creatorHook)
	case boil.BeforeUpdateHook:
		creatorBeforeUpdateHooks = append(creatorBeforeUpdateHooks, creatorHook)
	case boil.AfterUpdateHook:
		creatorAfterUpdateHooks = append(creatorAfterUpdateHooks, creatorHook)
	case boil.BeforeDeleteHook:
		creatorBeforeDeleteHooks = append(creatorBeforeDeleteHooks, creatorHook)
	case boil.AfterDeleteHook:
		creatorAfterDeleteHooks = append(creatorAfterDeleteHooks, creatorHook)
	case boil.BeforeUpsertHook:
		creatorBeforeUpsertHooks = append(creatorBeforeUpsertHooks, creatorHook)
	case boil.AfterUpsertHook:
		creatorAfterUpsertHooks = append(creatorAfterUpsertHooks, creatorHook)
	}
}

// OneG returns a single creator record from the query using the global executor.
func (q creatorQuery) OneG(ctx context.Context) (*Creator, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single creator record from the query.
func (q creatorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Creator, error) {
	o := &Creator{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for creator")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Creator records from the query using the global executor.
func (q creatorQuery) AllG(ctx context.Context) (CreatorSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Creator records from the query.
func (q creatorQuery) All(ctx context.Context, exec boil.ContextExecutor) (CreatorSlice, error) {
	var o []*Creator

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Creator slice")
	}

	if len(creatorAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Creator records in the query using the global executor
func (q creatorQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Creator records in the query.
func (q creatorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count creator rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q creatorQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q creatorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if creator exists")
	}

	return count > 0, nil
}

// Subs retrieves all the sub's Subs with an executor.
func (o *Creator) Subs(mods ...qm.QueryMod) subQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"sub\".\"creator_id\"=?", o.CreatorID),
	)

	return Subs(queryMods...)
}

// SubHistories retrieves all the sub_history's SubHistories with an executor.
func (o *Creator) SubHistories(mods ...qm.QueryMod) subHistoryQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"sub_history\".\"creator_id\"=?", o.CreatorID),
	)

	return SubHistories(queryMods...)
}

// LoadSubs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (creatorL) LoadSubs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCreator interface{}, mods queries.Applicator) error {
	var slice []*Creator
	var object *Creator

	if singular {
		var ok bool
		object, ok = maybeCreator.(*Creator)
		if !ok {
			object = new(Creator)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCreator)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCreator))
			}
		}
	} else {
		s, ok := maybeCreator.(*[]*Creator)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCreator)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCreator))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &creatorR{}
		}
		args = append(args, object.CreatorID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &creatorR{}
			}

			for _, a := range args {
				if a == obj.CreatorID {
					continue Outer
				}
			}

			args = append(args, obj.CreatorID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`sub`),
		qm.WhereIn(`sub.creator_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load sub")
	}

	var resultSlice []*Sub
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice sub")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on sub")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sub")
	}

	if len(subAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Subs = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &subR{}
			}
			foreign.R.Creator = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.CreatorID == foreign.CreatorID {
				local.R.Subs = append(local.R.Subs, foreign)
				if foreign.R == nil {
					foreign.R = &subR{}
				}
				foreign.R.Creator = local
				break
			}
		}
	}

	return nil
}

// LoadSubHistories allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (creatorL) LoadSubHistories(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCreator interface{}, mods queries.Applicator) error {
	var slice []*Creator
	var object *Creator

	if singular {
		var ok bool
		object, ok = maybeCreator.(*Creator)
		if !ok {
			object = new(Creator)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCreator)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCreator))
			}
		}
	} else {
		s, ok := maybeCreator.(*[]*Creator)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCreator)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCreator))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &creatorR{}
		}
		args = append(args, object.CreatorID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &creatorR{}
			}

			for _, a := range args {
				if a == obj.CreatorID {
					continue Outer
				}
			}

			args = append(args, obj.CreatorID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`sub_history`),
		qm.WhereIn(`sub_history.creator_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load sub_history")
	}

	var resultSlice []*SubHistory
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice sub_history")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on sub_history")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sub_history")
	}

	if len(subHistoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SubHistories = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &subHistoryR{}
			}
			foreign.R.Creator = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.CreatorID == foreign.CreatorID {
				local.R.SubHistories = append(local.R.SubHistories, foreign)
				if foreign.R == nil {
					foreign.R = &subHistoryR{}
				}
				foreign.R.Creator = local
				break
			}
		}
	}

	return nil
}

// AddSubsG adds the given related objects to the existing relationships
// of the creator, optionally inserting them as new records.
// Appends related to o.R.Subs.
// Sets related.R.Creator appropriately.
// Uses the global database handle.
func (o *Creator) AddSubsG(ctx context.Context, insert bool, related ...*Sub) error {
	return o.AddSubs(ctx, boil.GetContextDB(), insert, related...)
}

// AddSubs adds the given related objects to the existing relationships
// of the creator, optionally inserting them as new records.
// Appends related to o.R.Subs.
// Sets related.R.Creator appropriately.
func (o *Creator) AddSubs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Sub) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.CreatorID = o.CreatorID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"sub\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"creator_id"}),
				strmangle.WhereClause("\"", "\"", 2, subPrimaryKeyColumns),
			)
			values := []interface{}{o.CreatorID, rel.UserID, rel.CreatorID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.CreatorID = o.CreatorID
		}
	}

	if o.R == nil {
		o.R = &creatorR{
			Subs: related,
		}
	} else {
		o.R.Subs = append(o.R.Subs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &subR{
				Creator: o,
			}
		} else {
			rel.R.Creator = o
		}
	}
	return nil
}

// AddSubHistoriesG adds the given related objects to the existing relationships
// of the creator, optionally inserting them as new records.
// Appends related to o.R.SubHistories.
// Sets related.R.Creator appropriately.
// Uses the global database handle.
func (o *Creator) AddSubHistoriesG(ctx context.Context, insert bool, related ...*SubHistory) error {
	return o.AddSubHistories(ctx, boil.GetContextDB(), insert, related...)
}

// AddSubHistories adds the given related objects to the existing relationships
// of the creator, optionally inserting them as new records.
// Appends related to o.R.SubHistories.
// Sets related.R.Creator appropriately.
func (o *Creator) AddSubHistories(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SubHistory) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.CreatorID = o.CreatorID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"sub_history\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"creator_id"}),
				strmangle.WhereClause("\"", "\"", 2, subHistoryPrimaryKeyColumns),
			)
			values := []interface{}{o.CreatorID, rel.SubHistID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.CreatorID = o.CreatorID
		}
	}

	if o.R == nil {
		o.R = &creatorR{
			SubHistories: related,
		}
	} else {
		o.R.SubHistories = append(o.R.SubHistories, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &subHistoryR{
				Creator: o,
			}
		} else {
			rel.R.Creator = o
		}
	}
	return nil
}

// Creators retrieves all the records using an executor.
func Creators(mods ...qm.QueryMod) creatorQuery {
	mods = append(mods, qm.From("\"creator\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"creator\".*"})
	}

	return creatorQuery{q}
}

// FindCreatorG retrieves a single record by ID.
func FindCreatorG(ctx context.Context, creatorID int64, selectCols ...string) (*Creator, error) {
	return FindCreator(ctx, boil.GetContextDB(), creatorID, selectCols...)
}

// FindCreator retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCreator(ctx context.Context, exec boil.ContextExecutor, creatorID int64, selectCols ...string) (*Creator, error) {
	creatorObj := &Creator{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"creator\" where \"creator_id\"=$1", sel,
	)

	q := queries.Raw(query, creatorID)

	err := q.Bind(ctx, exec, creatorObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from creator")
	}

	if err = creatorObj.doAfterSelectHooks(ctx, exec); err != nil {
		return creatorObj, err
	}

	return creatorObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Creator) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Creator) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no creator provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(creatorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	creatorInsertCacheMut.RLock()
	cache, cached := creatorInsertCache[key]
	creatorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			creatorAllColumns,
			creatorColumnsWithDefault,
			creatorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(creatorType, creatorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(creatorType, creatorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"creator\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"creator\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into creator")
	}

	if !cached {
		creatorInsertCacheMut.Lock()
		creatorInsertCache[key] = cache
		creatorInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Creator record using the global executor.
// See Update for more documentation.
func (o *Creator) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Creator.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Creator) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	creatorUpdateCacheMut.RLock()
	cache, cached := creatorUpdateCache[key]
	creatorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			creatorAllColumns,
			creatorPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update creator, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"creator\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, creatorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(creatorType, creatorMapping, append(wl, creatorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update creator row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for creator")
	}

	if !cached {
		creatorUpdateCacheMut.Lock()
		creatorUpdateCache[key] = cache
		creatorUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q creatorQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q creatorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for creator")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for creator")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o CreatorSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CreatorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), creatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"creator\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, creatorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in creator slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all creator")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Creator) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Creator) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no creator provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(creatorColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	creatorUpsertCacheMut.RLock()
	cache, cached := creatorUpsertCache[key]
	creatorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			creatorAllColumns,
			creatorColumnsWithDefault,
			creatorColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			creatorAllColumns,
			creatorPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert creator, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(creatorPrimaryKeyColumns))
			copy(conflict, creatorPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"creator\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(creatorType, creatorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(creatorType, creatorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert creator")
	}

	if !cached {
		creatorUpsertCacheMut.Lock()
		creatorUpsertCache[key] = cache
		creatorUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Creator record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Creator) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Creator record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Creator) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Creator provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), creatorPrimaryKeyMapping)
	sql := "DELETE FROM \"creator\" WHERE \"creator_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from creator")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for creator")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q creatorQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q creatorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no creatorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from creator")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for creator")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o CreatorSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CreatorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(creatorBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), creatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"creator\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, creatorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from creator slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for creator")
	}

	if len(creatorAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Creator) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Creator provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Creator) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCreator(ctx, exec, o.CreatorID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CreatorSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty CreatorSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CreatorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CreatorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), creatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"creator\".* FROM \"creator\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, creatorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CreatorSlice")
	}

	*o = slice

	return nil
}

// CreatorExistsG checks if the Creator row exists.
func CreatorExistsG(ctx context.Context, creatorID int64) (bool, error) {
	return CreatorExists(ctx, boil.GetContextDB(), creatorID)
}

// CreatorExists checks if the Creator row exists.
func CreatorExists(ctx context.Context, exec boil.ContextExecutor, creatorID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"creator\" where \"creator_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, creatorID)
	}
	row := exec.QueryRowContext(ctx, sql, creatorID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if creator exists")
	}

	return exists, nil
}
